/* eslint-disable max-lines */
/* eslint-disable max-lines-per-function */
import type { Config } from 'tailwindcss'
import plugin from 'tailwindcss/plugin'

const config: Config = {
	content: ['./src/**/*.{js,ts,jsx,tsx,mdx}', './pages/**/*.{js,ts,jsx,tsx,mdx}'],
	theme: {
		extend: {
			colors: {
				primary: 'rgb(var(--color-primary) / <alpha-value>)',
				'on-primary': 'rgb(var(color-on-primary) / <alpha-value>)',
				'primary-container': 'rgb(var(--color-primary-container) / <alpha-value>)',
				'on-primary-container': 'rgb(var(--color-on-primary-container) / <alpha-value>)',
				'on-surface': 'rgb(var(--color-on-surface) / <alpha-value>)',
				'on-surface-dim': 'rgb(var(--color-on-surface-dim) / <alpha-value>)',
				outline: 'rgb(var(--color-outline) / <alpha-value>)',
				'outline-dim': 'rgb(var(--color-outline-dim) / <alpha-value>)',
				scrim: 'rgb(var(--color-scrim) / <alpha-value>)',
				shadow: 'rgb(var(--color-shadow) / <alpha-value>)',
				background: 'rgb(var(--color-background) / <alpha-value>)',
				'surface-lowest': 'rgb(var(--color-surface-lowest) / <alpha-value>)',
				'surface-low': 'rgb(var(--color-surface-low) / <alpha-value>)',
				'surface-medium': 'rgb(var(--color-surface-medium) / <alpha-value>)',
				'surface-high': 'rgb(var(--color-surface-high) / <alpha-value>)',
				'surface-highest': 'rgb(var(--color-surface-highest) / <alpha-value>)',
				'inverse-surface': 'rgb(var(--color-inverse-surface) / <alpha-value>)',
				'inverse-on-surface': 'rgb(var(--color-inverse-on-surface) / <alpha-value>)',
				'inverse-primary': 'rgb(var(--color-inverse-primary) / <alpha-value>)',
			},
			fontFamily: {
				'display-large': 'var(--typescale-display-large-font)',
				'display-medium': 'var(--typescale-display-medium-font)',
				'display-small': 'var(--typescale-display-small-font)',
				'headline-large': 'var(--typescale-headline-large-font)',
				'headline-medium': 'var(--typescale-headline-medium-font)',
				'headline-small': 'var(--typescale-headline-small-font)',
				'title-large': 'var(--typescale-title-large-font)',
				'title-medium': 'var(--typescale-title-medium-font)',
				'title-small': 'var(--typescale-title-small-font)',
				'label-large': 'var(--typescale-label-large-font)',
				'label-medium': 'var(--typescale-label-medium-font)',
				'label-small': 'var(--typescale-label-small-font)',
				'body-large': 'var(--typescale-body-large-font)',
				'body-medium': 'var(--typescale-body-medium-font)',
				'body-small': 'var(--typescale-body-small-font)',
			},
			lineHeight: {
				'display-large': 'var(--typescale-display-large-line-height)',
				'display-medium': 'var(--typescale-display-medium-line-height)',
				'display-small': 'var(--typescale-display-small-line-height)',
				'headline-large': 'var(--typescale-headline-large-line-height)',
				'headline-medium': 'var(--typescale-headline-medium-line-height)',
				'headline-small': 'var(--typescale-headline-small-line-height)',
				'title-large': 'var(--typescale-title-large-line-height)',
				'title-medium': 'var(--typescale-title-medium-line-height)',
				'title-small': 'var(--typescale-title-small-line-height)',
				'label-large': 'var(--typescale-label-large-line-height)',
				'label-medium': 'var(--typescale-label-medium-line-height)',
				'label-small': 'var(--typescale-label-small-line-height)',
				'body-large': 'var(--typescale-body-large-line-height)',
				'body-medium': 'var(--typescale-body-medium-line-height)',
				'body-small': 'var(--typescale-body-small-line-height)',
			},
			fontWeight: {
				'display-large': 'var(--typescale-display-large-weight)',
				'display-medium': 'var(--typescale-display-medium-weight)',
				'display-small': 'var(--typescale-display-small-weight)',
				'headline-large': 'var(--typescale-headline-large-weight)',
				'headline-medium': 'var(--typescale-headline-medium-weight)',
				'headline-small': 'var(--typescale-headline-small-weight)',
				'title-large': 'var(--typescale-title-large-weight)',
				'title-medium': 'var(--typescale-title-medium-weight)',
				'title-small': 'var(--typescale-title-small-weight)',
				'label-large': 'var(--typescale-label-large-weight)',
				'label-medium': 'var(--typescale-label-medium-weight)',
				'label-small': 'var(--typescale-label-small-weight)',
				'body-large': 'var(--typescale-body-large-weight)',
				'body-medium': 'var(--typescale-body-medium-weight)',
				'body-small': 'var(--typescale-body-small-weight)',
			},
			fontSize: {
				'display-large': 'var(--typescale-display-large-size)',
				'display-medium': 'var(--typescale-display-medium-size)',
				'display-small': 'var(--typescale-display-small-size)',
				'headline-large': 'var(--typescale-headline-large-size)',
				'headline-medium': 'var(--typescale-headline-medium-size)',
				'headline-small': 'var(--typescale-headline-small-size)',
				'title-large': 'var(--typescale-title-large-size)',
				'title-medium': 'var(--typescale-title-medium-size)',
				'title-small': 'var(--typescale-title-small-size)',
				'label-large': 'var(--typescale-label-large-size)',
				'label-medium': 'var(--typescale-label-medium-size)',
				'label-small': 'var(--typescale-label-small-size)',
				'body-large': 'var(--typescale-body-large-size)',
				'body-medium': 'var(--typescale-body-medium-size)',
				'body-small': 'var(--typescale-body-small-size)',
			},
			letterSpacing: {
				'display-large': 'var(--typescale-display-large-tracking)',
				'display-medium': 'var(--typescale-display-medium-tracking)',
				'display-small': 'var(--typescale-display-small-tracking)',
				'headline-large': 'var(--typescale-headline-large-tracking)',
				'headline-medium': 'var(--typescale-headline-medium-tracking)',
				'headline-small': 'var(--typescale-headline-small-tracking)',
				'title-large': 'var(--typescale-title-large-tracking)',
				'title-medium': 'var(--typescale-title-medium-tracking)',
				'title-small': 'var(--typescale-title-small-tracking)',
				'label-large': 'var(--typescale-label-large-tracking)',
				'label-medium': 'var(--typescale-label-medium-tracking)',
				'label-small': 'var(--typescale-label-small-tracking)',
				'body-large': 'var(--typescale-body-large-tracking)',
				'body-medium': 'var(--typescale-body-medium-tracking)',
				'body-small': 'var(--typescale-body-small-tracking)',
			},
			boxShadow: {
				none: 'var(--shadow-none)',
				'extra-small': 'var(--shadow-extra-small)',
				small: 'var(--shadow-small)',
				medium: 'var(--shadow-medium)',
				large: 'var(--shadow-large)',
				'extra-large': 'var(--shadow-extra-large)',
			},
			transitionTimingFunction: {
				emphasized: 'var(--easing-emphasized)',
				'emphasized-decelerate': 'var(--easing-emphasized-decelerate)',
				'emphasized-accelerate': 'var(--easing-emphasized-accelerate)',
				standard: 'var(--easing-standard)',
				'standard-decelerate': 'var(--easing-standard-decelerate)',
				'standard-accelerate': 'var(--easing-standard-accelerate)',
			},
			transitionDuration: {
				1: 'var(--duration-1)',
				2: 'var(--duration-2)',
				3: 'var(--duration-3)',
				4: 'var(--duration-4)',
				5: 'var(--duration-5)',
				6: 'var(--duration-6)',
				7: 'var(--duration-7)',
				8: 'var(--duration-8)',
				9: 'var(--duration-9)',
				10: 'var(--duration-10)',
				11: 'var(--duration-11)',
				12: 'var(--duration-12)',
				13: 'var(--duration-13)',
				14: 'var(--duration-14)',
				15: 'var(--duration-15)',
				16: 'var(--duration-16)',
			},
			opacity: {
				hovered: 'var(--state-opacity-hovered)',
				pressed: 'var(--state-opacity-pressed)',
				focused: 'var(--state-opacity-focused)',
				dragged: 'var(--state-opacity-dragged)',
				'disabled-content': 'var(--state-opacity-disabled-content)',
				'disabled-container': 'var(--state-opacity-disabled-container)',
			},
		},
	},
	plugins: [
		plugin(({ addUtilities, theme }) => {
			addUtilities({
				'.typescale-display-large': {
					fontFamily: theme('fontFamily.display-large'),
					lineHeight: theme('lineHeight.display-large'),
					fontWeight: theme('fontWeight.display-large'),
					fontSize: theme('fontSize.display-large'),
					letterSpacing: theme('letterSpacing.display-large'),
				},
				'.typescale-display-medium': {
					fontFamily: theme('fontFamily.display-medium'),
					lineHeight: theme('lineHeight.display-medium'),
					fontWeight: theme('fontWeight.display-medium'),
					fontSize: theme('fontSize.display-medium'),
					letterSpacing: theme('letterSpacing.display-medium'),
				},
				'.typescale-display-small': {
					fontFamily: theme('fontFamily.display-small'),
					lineHeight: theme('lineHeight.display-small'),
					fontWeight: theme('fontWeight.display-small'),
					fontSize: theme('fontSize.display-small'),
					letterSpacing: theme('letterSpacing.display-small'),
				},
				'.typescale-headline-large': {
					fontFamily: theme('fontFamily.headline-large'),
					lineHeight: theme('lineHeight.headline-large'),
					fontWeight: theme('fontWeight.headline-large'),
					fontSize: theme('fontSize.headline-large'),
					letterSpacing: theme('letterSpacing.headline-large'),
				},
				'.typescale-headline-medium': {
					fontFamily: theme('fontFamily.headline-medium'),
					lineHeight: theme('lineHeight.headline-medium'),
					fontWeight: theme('fontWeight.headline-medium'),
					fontSize: theme('fontSize.headline-medium'),
					letterSpacing: theme('letterSpacing.headline-medium'),
				},
				'.typescale-headline-small': {
					fontFamily: theme('fontFamily.headline-small'),
					lineHeight: theme('lineHeight.headline-small'),
					fontWeight: theme('fontWeight.headline-small'),
					fontSize: theme('fontSize.headline-small'),
					letterSpacing: theme('letterSpacing.headline-small'),
				},
				'.typescale-title-large': {
					fontFamily: theme('fontFamily.title-large'),
					lineHeight: theme('lineHeight.title-large'),
					fontWeight: theme('fontWeight.title-large'),
					fontSize: theme('fontSize.title-large'),
					letterSpacing: theme('letterSpacing.title-large'),
				},
				'.typescale-title-medium': {
					fontFamily: theme('fontFamily.title-medium'),
					lineHeight: theme('lineHeight.title-medium'),
					fontWeight: theme('fontWeight.title-medium'),
					fontSize: theme('fontSize.title-medium'),
					letterSpacing: theme('letterSpacing.title-medium'),
				},
				'.typescale-title-small': {
					fontFamily: theme('fontFamily.title-small'),
					lineHeight: theme('lineHeight.title-small'),
					fontWeight: theme('fontWeight.title-small'),
					fontSize: theme('fontSize.title-small'),
					letterSpacing: theme('letterSpacing.title-small'),
				},
				'.typescale-label-large': {
					fontFamily: theme('fontFamily.label-large'),
					lineHeight: theme('lineHeight.label-large'),
					fontWeight: theme('fontWeight.label-large'),
					fontSize: theme('fontSize.label-large'),
					letterSpacing: theme('letterSpacing.label-large'),
				},
				'.typescale-label-medium': {
					fontFamily: theme('fontFamily.label-medium'),
					lineHeight: theme('lineHeight.label-medium'),
					fontWeight: theme('fontWeight.label-medium'),
					fontSize: theme('fontSize.label-medium'),
					letterSpacing: theme('letterSpacing.label-medium'),
				},
				'.typescale-label-small': {
					fontFamily: theme('fontFamily.label-small'),
					lineHeight: theme('lineHeight.label-small'),
					fontWeight: theme('fontWeight.label-small'),
					fontSize: theme('fontSize.label-small'),
					letterSpacing: theme('letterSpacing.label-small'),
				},
				'.typescale-body-large': {
					fontFamily: theme('fontFamily.body-large'),
					lineHeight: theme('lineHeight.body-large'),
					fontWeight: theme('fontWeight.body-large'),
					fontSize: theme('fontSize.body-large'),
					letterSpacing: theme('letterSpacing.body-large'),
				},
				'.typescale-body-medium': {
					fontFamily: theme('fontFamily.body-medium'),
					lineHeight: theme('lineHeight.body-medium'),
					fontWeight: theme('fontWeight.body-medium'),
					fontSize: theme('fontSize.body-medium'),
					letterSpacing: theme('letterSpacing.body-medium'),
				},
				'.typescale-body-small': {
					fontFamily: theme('fontFamily.body-small'),
					lineHeight: theme('lineHeight.body-small'),
					fontWeight: theme('fontWeight.body-small'),
					fontSize: theme('fontSize.body-small'),
					letterSpacing: theme('letterSpacing.body-small'),
				},
				'.elevation-none': {
					boxShadow: theme('boxShadow.none'),
					backgroundColor: 'rgb(var(--color-background))',
				},
				'.elevation-lowest': {
					boxShadow: theme('boxShadow.small'),
					backgroundColor: 'rgb(var(--color-surface-lowest))',
				},
				'.elevation-low': {
					boxShadow: theme('boxShadow.small'),
					backgroundColor: 'rgb(var(--color-surface-low))',
				},
				'.elevation-medium': {
					boxShadow: theme('boxShadow.medium'),
					backgroundColor: 'rgb(var(--color-surface-medium))',
				},
				'.elevation-high': {
					boxShadow: theme('boxShadow.large'),
					backgroundColor: 'rgb(var(--color-surface-high))',
				},
				'.elevation-highest': {
					boxShadow: theme('boxShadow.extra-large'),
					backgroundColor: 'rgb(var(--color-surface-highest))',
				},
			})
		}),
	],
}

export default config
